project_id = "cssnxomfkrnjaedoobjj"

[functions.generate-content]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false

[functions.vision-guide]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
