/**
 * src/hooks/useDawnPatrol.ts — React Query hooks for Dawn Patrol.
 *
 * Mirrors useGhostCredits: exposes refresh + generate + markRead +
 * config get/set. Polls latest briefs every 5 min while the user is
 * on the Dashboard so sunrise deliveries surface within one refresh
 * of being generated by pg_cron.
 */
import { useCallback, useEffect, useRef } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { fetchEdgeFunctionJson } from "@/api/client/secureClient";
import { useDawnPatrolStore, type DawnBrief } from "@/stores/useDawnPatrolStore";
import { useAuthStore } from "@/stores/useAuthStore";

interface LatestResponse {
  success: boolean;
  briefs: DawnBrief[];
}
interface GenerateResponse {
  success: boolean;
  briefId?: string;
  headline?: string;
  bullets?: string[];
  opportunities?: string[];
  threats?: string[];
  error?: string;
  code?: string;
}
interface ConfigResponse { success: boolean; config: { enabled: boolean; send_hour: number }; }

export function useDawnPatrol() {
  const queryClient = useQueryClient();
  const isAuthed = !!useAuthStore((s) => s.user);
  const hydrate = useDawnPatrolStore((s) => s.hydrate);
  const setError = useDawnPatrolStore((s) => s.setError);
  const setGenerating = useDawnPatrolStore((s) => s.setGenerating);
  const setConfig = useDawnPatrolStore((s) => s.setConfig);
  const markReadLocal = useDawnPatrolStore((s) => s.markReadLocal);
  const prevHeadlineRef = useRef<string | null>(null);

  const latestKey = ["ghost", "dawn-patrol", "latest"] as const;

  const { data, isLoading, refetch } = useQuery({
    queryKey: latestKey,
    queryFn: async () => {
      const r = await fetchEdgeFunctionJson<LatestResponse>("ghost/dawn-patrol-latest", { n: 7 });
      if (!r.success) throw new Error("Failed to load Dawn Patrol");
      const briefs = Array.isArray(r.briefs) ? r.briefs : [];
      // Detect new brief: if top headline changed from what we've seen locally, fire a toast.
      if (briefs.length > 0) {
        const top = briefs[0];
        if (prevHeadlineRef.current && prevHeadlineRef.current !== top.headline && !top.read_at) {
          toast(`🌅 Dawn Patrol: ${top.headline}`, {
            description: (top.bullets?.[0] ?? "").slice(0, 120),
            duration: 6000,
          });
        }
        prevHeadlineRef.current = top.headline;
      }
      hydrate(briefs);
      return briefs;
    },
    enabled: isAuthed,
    refetchInterval: 5 * 60 * 1000, // 5 min
    refetchOnWindowFocus: true,
    staleTime: 60 * 1000,
    retry: 1,
  });

  useEffect(() => {
    if (isLoading) return;
    useDawnPatrolStore.getState().setLoading(isLoading);
  }, [isLoading]);

  // Config fetch on mount (once, best effort).
  useEffect(() => {
    if (!isAuthed) return;
    let cancelled = false;
    (async () => {
      try {
        const r = await fetchEdgeFunctionJson<ConfigResponse>("ghost/dawn-patrol-config", {});
        if (!cancelled && r?.config) setConfig(r.config);
      } catch {
        /* non-fatal */
      }
    })();
    return () => { cancelled = true; };
  }, [isAuthed, setConfig]);

  const generate = useMutation({
    mutationFn: async (args?: { niche?: string; competitors?: any[]; prevBrief?: any }) => {
      setGenerating(true);
      return fetchEdgeFunctionJson<GenerateResponse>("ghost/dawn-patrol-generate", {
        niche: args?.niche,
        competitors: args?.competitors ?? [],
        prevBrief: args?.prevBrief ?? null,
      });
    },
    onSuccess: (r) => {
      setGenerating(false);
      if (!r.success) {
        toast.error(r.error || "Dawn Patrol failed");
        setError(r.error || "generate failed");
        return;
      }
      toast.success(`🌅 Dawn Patrol: ${r.headline ?? "ready"}`);
      void queryClient.invalidateQueries({ queryKey: latestKey });
    },
    onError: (e: any) => {
      setGenerating(false);
      const msg = e?.message || "Dawn Patrol failed";
      setError(msg);
      toast.error(msg);
    },
  });

  const markRead = useCallback(async (id: string) => {
    markReadLocal(id);
    try {
      await fetchEdgeFunctionJson("ghost/dawn-patrol-mark-read", { id });
    } catch {
      /* non-fatal — local mark stays */
    }
  }, [markReadLocal]);

  const saveConfig = useCallback(async (cfg: { enabled: boolean; send_hour: number }) => {
    try {
      const r = await fetchEdgeFunctionJson<ConfigResponse>("ghost/dawn-patrol-config", {
        enabled: cfg.enabled, sendHour: cfg.send_hour,
      });
      if (r?.config) setConfig(r.config);
      toast.success("Dawn Patrol preferences saved");
      return r?.config;
    } catch (e: any) {
      toast.error(e?.message || "Save failed");
      return null;
    }
  }, [setConfig]);

  return {
    briefs: data ?? [],
    isLoading,
    refetch,
    generate,
    markRead,
    saveConfig,
  };
}
