// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getPinnedUserId, pinUserId } from '@/lib/storage/perUserStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Per-user namespaced auth/session storage.
//
// Why: Supabase persists its session (access+refresh JWTs) under a fixed
// sb-<project>-auth-token key by default. On a shared device that means
// User A's refresh token can be read into User B's session on a stale
// hydration. This adapter stores the Supabase token blob under a
// user-id-namespaced key derived from the SAME durable pin
// (`tc:last-auth-user-id`) that the zustand perUserStorage uses — so
// tokens AND app-state always move together between guest/user slots,
// and there is zero window where the JS layer thinks a different user
// is signed in than Supabase does.
const SB_AUTH_KEY_BASE = `sb-auth-token:${btoa(SUPABASE_URL || "").slice(0, 16)}`;
function namespacedKeyFor(uid: string | null): string {
  if (uid) return `${SB_AUTH_KEY_BASE}:u:${uid}`;
  return `${SB_AUTH_KEY_BASE}:guest`;
}
function currentNamespacedKey(): string {
  return namespacedKeyFor(getPinnedUserId());
}
const namespacedAuthStorage: {
  getItem: (key: string) => string | null;
  setItem: (key: string, value: string) => void;
  removeItem: (key: string) => void;
} = {
  getItem: () => {
    try { return localStorage.getItem(currentNamespacedKey()); } catch { return null; }
  },
  setItem: (_key, value) => {
    try {
      // When Supabase persists a new session, extract the user id and pin
      // future reads/writes to that user's namespace BEFORE computing the
      // key so we never write the new session into the old user's bucket.
      let userId: string | null = null;
      try {
        const parsed = JSON.parse(value);
        userId = parsed?.user?.id ?? null;
      } catch {}
      pinUserId(userId);
      localStorage.setItem(namespacedKeyFor(userId), value);
    } catch {}
  },
  removeItem: () => {
    try {
      const key = currentNamespacedKey();
      localStorage.removeItem(key);
      pinUserId(null);
    } catch {}
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: namespacedAuthStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Stay on the OAuth flow the provider returned; PKCE code exchange is
    // handled by supabase-js once initialize()/getSession() is called.
    flowType: "pkce",
  },
});
